# Generated by Django 6.0.2 on 2026-02-10 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organiser',
            old_name='Organiser_id',
            new_name='organiser_id',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='User_id',
            new_name='user_id',
        ),
    ]
