# Generated by Django 6.0.2 on 2026-02-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_organiser_id_organiser_organiser_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organiser',
            name='phone',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
