# Generated by Django 6.0.2 on 2026-02-11 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_organiser_phone_alter_user_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='organisers',
            new_name='organisers_id',
        ),
    ]
