# Generated by Django 6.0.2 on 2026-02-11 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_rename_organisers_event_organisers_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='available_seat',
            new_name='available_seats',
        ),
    ]
